version: v0.1
testId: openasr-smoke-test
testPlan: test-plans/smoke/smoke-test.jmx
engineInstances: 1
configurationFiles:
  - data/audio/sample-short-5s.raw
  - data/speech-configs.csv
  - properties/staging.properties
zipArtifacts:
  - plugins/jmeter-websocket-samplers-1.3.1.jar
  - fragments/ws-connect-and-config.jmx
  - fragments/ws-send-audio.jmx
  - fragments/ws-receive-results.jmx
  - fragments/ws-teardown.jmx
failureCriteria:
  - avg(response_time_ms) > 3000
  - percentage(error) > 1
