apiVersion: v1
kind: Namespace
metadata:
  name: whisperx
  labels:
    app.kubernetes.io/name: whisperx
    app.kubernetes.io/part-of: whisperx-streaming-server
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
